---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  roles:
    - configure-server
    - configure-prometheus-node-exporter
    
  pre_tasks:
    # - name: "wait 600 seconds for target connection to become reachable/usable."

    - name: "install python for Ansible."
      become: yes
      apt:
        name: python3

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.cac1ecrqianq.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    TYPEORM_DATABASE: postgres