---
- name: "Udapeople Server Configurations"
  hosts: all
  user: ubuntu
 
  vars:
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: False
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.cac1ecrqianq.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    TYPEORM_DATABASE: postgres

  gather_facts: true

  roles:
    - configure-server
    - db-rollback