- name: "install node 14.X"
  become: true
  shell: |
    cd ~
    curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
    sudo sh ./setup_14.sh
    sudo apt -y upgrade
    sudo apt install -y nodejs

- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 