- name: "test that ansible works"
  shell: |
    echo "hello mate"

- name: "Ansible shell module multiple commands"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: "install node 14.X"
  become: true
  shell: |
    sudo apt -y upgrade
    sudo apt install -y nodejs

- name: Install reqired packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - curl
    - wget
    - nginx
    - nodejs

- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 